[package]
name = "basic-http-server"
version = "0.1.0"
authors = ["Brian Anderson <banderson@mozilla.com>"]
license = "MIT/Apache-2.0"

[dependencies]
rotor = {git="git://github.com/tailhook/rotor", rev="4c142d4"}
rotor-stream = {git="git://github.com/tailhook/rotor-stream", rev="2628e69"}
rotor-http = {git="git://github.com/tailhook/rotor-http", rev="a855cdaab"}
mio = "0.5"
time = "0.1"
clap = "1.5.5"
threadpool = "0.2.1"
net2 = "0.2"
libc = "0.2.4"
error-type = "0.1.2"
