[package]
name = "basic-http-server"
version = "0.6.3"
authors = ["Brian Anderson <andersrb@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A simple static HTTP file server, for learning and local doc development"
homepage = "https://github.com/brson/basic-http-server"
repository = "https://github.com/brson/basic-http-server"
readme = "README.md"
edition = "2018"

[dependencies]
clap = "2.33.0"
comrak = "0.6.2"
derive_more = "0.15.0"
env_logger = "0.6.2"
futures = "0.3.1"
handlebars = "1.1.0"
http = "0.1.19"
hyper = "0.13.0-alpha.4"
log = "0.4.8"
mime = "0.3.14"
percent-encoding = "2.1.0"
serde = "1.0.102"
serde_derive = "1.0.102"
tokio = "0.2.0-alpha.6"
tokio-fs = "0.2.0-alpha.6"
structopt = "0.2.18"
