[package]
name = "basic-http-server"
version = "0.1.0"
authors = ["Brian Anderson <banderson@mozilla.com>"]
license = "MIT/Apache-2.0"

[dependencies]
rotor = "0.6.0"
rotor-http = "0.6.0"
clap = "1.5.5"
threadpool = "0.2.1"
net2 = "0.2"
libc = "0.2.4"
error-type = "0.1.2"
